# nginx-chart/values.yaml
replicaCount: 1
image:
  repository: nginx
  tag: "1.19.6"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
labels:
  app: custom-app
  name: custom-name
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi