apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-1
spec:
  destination:
    name: ''
    namespace: demo-namespace
    server: https://kubernetes.default.svc
  source:
    path: nginx-1
    repoURL: https://github.com/NikolaosEfthymiou/argocd-example.git
    targetRevision: HEAD
  sources: []
  project: my-project
