# nginx-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labels.name }}
  labels:
    service: {{ .Values.labels.service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: {{ .Values.labels.service }}
  template:
    metadata:
      labels:
        service: {{ .Values.labels.service }}
    spec:
      containers:
        - name: {{ .Values.labels.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
{{ toYaml .Values.resources | indent 12 }}